### ISSUE TITLE
Get A Shader Person To Help Us

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#320]
### Description

![image](https://github.com/ThetaStation/ThetaStation/assets/17705613/e729f895-681a-4818-b23d-718e6f4ad22b)

I have no idea what this means, but because of this one player with very old drivers could not join our server.

**Comment by KIBORG04** [comment]
```
Unhandled exception. Robust.Client.Graphics.Clyde.ShaderCompilationException: Failed to compile vertex shader, see inner for details (and error.glsl for formatted source).
 ---> Robust.Client.Graphics.Clyde.ShaderCompilationException: ERROR: 0:168: 'uniform' :  cannot initialize this type of qualifier 
ERROR: 0:169: 'uniform' :  cannot initialize this type of qualifier 
ERROR: 0:170: 'uniform' :  cannot initialize this type of qualifier 

   at Robust.Client.Graphics.Clyde.Clyde.GLShader.Compile(ShaderType type, String shaderSource) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/Graphics/Clyde/GLObjects/Clyde.Shader.cs:line 40
   at Robust.Client.Graphics.Clyde.Clyde.GLShader..ctor(Clyde clyde, ShaderType type, String shaderSource, String name) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/Graphics/Clyde/GLObjects/Clyde.Shader.cs:line 14
   at Robust.Client.Graphics.Clyde.Clyde._compileProgram(String vertexSource, String fragmentSource, ValueTuple`2[] attribLocations, String name, Boolean includeLib, Dictionary`2 defines) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.Shaders.cs:line 236
   --- End of inner exception stack trace ---
   at Robust.Client.Graphics.Clyde.Clyde._compileProgram(String vertexSource, String fragmentSource, ValueTuple`2[] attribLocations, String name, Boolean includeLib, Dictionary`2 defines) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.Shaders.cs:line 241
   at Robust.Client.Graphics.Clyde.Clyde.LoadShader(ParsedShader shader, String name, Dictionary`2 defines) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.Shaders.cs:line 91
   at Robust.Client.ResourceManagement.ShaderSourceResource.Load(IResourceCache cache, ResPath path) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/ResourceManagement/ResourceTypes/ShaderSourceResource.cs:line 31
   at Robust.Client.ResourceManagement.ResourceCache.GetResource[T](ResPath path, Boolean useFallback) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/ResourceManagement/ResourceCache.cs:line 36
   at Robust.Client.Graphics.ShaderPrototype.Robust.Shared.Serialization.ISerializationHooks.AfterDeserialization() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/Graphics/Shaders/ShaderPrototype.cs:line 110
   at Robust.Shared.Prototypes.PrototypeManager.ResolveResults() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Prototypes/PrototypeManager.cs:line 451
   at Robust.Client.Prototypes.ClientPrototypeManager.LoadDefaultPrototypes(Dictionary`2 changed) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/Prototypes/ClientPrototypeManager.cs:line 49
   at Robust.Client.GameController.StartupContinue(DisplayMode displayMode) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.cs:line 166
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 127
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 119
   at Robust.Client.GameController.<>c__DisplayClass99_0.<Run>b__0() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 86
   at System.Threading.Thread.StartCallback()
   ```
